# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# environment variables
environment:
  matrix:
    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_MAJOR: 3
      PYTHON_ARCH: "64"

# scripts that run after cloning repository
install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
      https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
      Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }

  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda install pip
  - pip install invoke
  - conda install pyyaml

build: off

test_script:
  - 'invoke environment'
  - 'invoke demofiles'
  - 'invoke talk -t demo'
  - 'invoke clean'
