channels:
- QuantStack
- conda-forge
dependencies:
- jupyterlab=0.34.0
- nodejs=8.9
- notebook=5.6
- nbconvert=5.3
- ipykernel=4.7
- ipywidgets=7.3
- ipyleaflet=0.9
- widgetsnbextension=3.3
- altair=1.2
- bqplot=0.11
- dask=0.15
- matplotlib=2.1
- pandas=0.20
- python=3.6
- scikit-image=0.13
- scikit-learn=0.18
- seaborn=0.7
- tensorflow=1.1
- sympy=1.0
- pyyaml
- traittypes==0.2.1
- invoke=0.21
- xeus-cling=0.4.5
- xtensor=0.17.0
- xtensor-blas=0.12
- xwidgets=0.12.2
- xleaflet=0.2.1
- r-ggplot2
- r-irkernel=0.8.11
